spring:
  application:
    name: asset-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/predictive_maintenance
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 5
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      compression-type: gzip
    properties:
      max.in.flight.requests.per.connection: 5
      enable.idempotence: true

  jpa:
    hibernate:
      ddl-auto: validate # use 'update' for dev, 'validate' for prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.assetmanagement: DEBUG
  file:
    name: logs/asset-management.log
